{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fasterxml.jackson.core",
    "module": "jackson-databind",
    "version": "2.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "maven": {
      "version": "3.8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.15.1.jar",
          "url": "jackson-databind-2.15.1.jar",
          "size": 1620059,
          "sha512": "a6750ced73427dd1a618501e8b0b08ab0799ea878e2317ecce3cd0dbf844d472e06fe5914d70ce34d54553e894f97fd09e6ce040cb9aef4b4b1a8d1e9198755",
          "sha256": "c1f0347ce2696c94f531d095cd9ef22e648ec090e9b1c3dee17938b07a1df176",
          "sha1": "ac9ba74d208faf356e4719a49e59c6ea9237c01d",
          "md5": "2f4071cd666983bef73a25b9a1ad2d8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.fasterxml.jackson",
          "module": "jackson-bom",
          "version": {
            "requires": "2.15.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        }
      ],
      "files": [
        {
          "name": "jackson-databind-2.15.1.jar",
          "url": "jackson-databind-2.15.1.jar",
          "size": 1620059,
          "sha512": "a6750ced73427dd1a618501e8b0b08ab0799ea878e2317ecce3cd0dbf844d472e06fe5914d70ce34d54553e894f97fd09e6ce040cb9aef4b4b1a8d1e9198755",
          "sha256": "c1f0347ce2696c94f531d095cd9ef22e648ec090e9b1c3dee17938b07a1df176",
          "sha1": "ac9ba74d208faf356e4719a49e59c6ea9237c01d",
          "md5": "2f4071cd666983bef73a25b9a1ad2d8"
        }
      ]
    }
  ]
}
